import Header from '@/components/UI/Header'
import Loader from '@/components/UI/Loader'
import InputModel from '@/components/InputModel'
import TextareaModel from '@/components/TextareaModel'
import PostList from '@/components/postComponents/PostList'
import Post from '@/components/postComponents/Post'
import PostSearch from '@/components/postComponents/PostSearch'
import ItemList from '@/components/postComponents/ItemList'
import AddItemList from '@/components/postComponents/AddItemList'
import CommentItem from '@/components/commentComponents/CommentItem'
import CommentList from '@/components/commentComponents/CommentList'
import CreateNewComment from '@/components/commentComponents/CreateNewComment'
import Sidebar from '@/components/sidebarComponents/Sidebar.vue'
import SidebarCategories from '@/components/sidebarComponents/SidebarCategories.vue'
import SidebarLinks from '@/components/sidebarComponents/SidebarLinks.vue'
import CategoriesSelected from '@/components/categoriesComponents/CategoriesSelected.vue'
import UploadImage from '@/components/UploadImage.vue'
import LoginForm from '@/components/authComponents/LoginForm.vue'
import RegistrationForm from '@/components/authComponents/RegistrationForm.vue'
import FormStyled from '@/components/authComponents/FormStyled.vue'
import SidebarAdminLinks from '@/components/sidebarComponents/SidebarAdminLinks.vue'
import CategoryList from '@/components/categoriesComponents/CategoryList.vue'
import CategoryPreview from '@/components/categoriesComponents/CategoryPreview.vue'
import EditButton from '@/components/UI/EditButton.vue'
import FavoritesButton from '@/components/UI/FavoritesButton.vue'
import DeleteButton from '@/components/UI/DeleteButton.vue'
import ConfirmButton from '@/components/UI/ConfirmButton.vue'
import DeletePopup from '@/components/UI/DeletePopup.vue'
import ActivationPopup from '@/components/UI/ActivationPopup.vue'
import CategorySearch from '@/components/categoriesComponents/CategorySearch.vue'
import CategoryItem from '@/components/categoriesComponents/CategoryItem.vue'
import UsersList from '@/components/usersComponents/UsersList.vue'
import UserItem from '@/components/usersComponents/UserItem.vue'
import RoleSelected from '@/components/usersComponents/RoleSelected.vue'
import UsersSearch from '@/components/usersComponents/UsersSearch.vue'

export default [Header,PostList,Post,SidebarLinks,Sidebar,SidebarCategories,CommentItem,InputModel,Loader,CategoriesSelected,UploadImage,TextareaModel,ItemList,AddItemList,LoginForm,RegistrationForm,FormStyled,SidebarAdminLinks,CategoryList,EditButton,DeleteButton,CategorySearch,ConfirmButton,CategoryItem,UsersList,UserItem,RoleSelected,CategoryPreview,DeletePopup,PostSearch,UsersSearch,FavoritesButton,CommentList,CreateNewComment,ActivationPopup]
    